<?php

/**
 * AuditLog Controller
 *
 * Read-only module. Renders the activity log index with server-side filters
 * and provides a PDF export endpoint.
 *
 * @package ProyectoBase
 * @subpackage App\Controllers
 * @author jandrescodes
 * @version 1.0
 */

namespace App\Controllers;

use App\Core\Auth;
use App\Core\Controller;
use App\Models\ActivityLog;
use App\Services\AuditLogger;
use App\Services\AuditLogPdfExporter;

class AuditLogController extends Controller
{
    private ActivityLog $logModel;

    public function __construct()
    {
        $this->logModel = new ActivityLog();
    }

    /**
     * Renders the audit log index page.
     */
    public function index(): void
    {
        $activeFilters = $this->readFilters();

        $logs    = $this->logModel->getAll($activeFilters);
        $modules = $this->logModel->getDistinctModules();
        $actions = $this->logModel->getDistinctActions();
        $actors  = $this->logModel->getActorsWithLogs();
        $filters = $this->rawFilters();

        $this->render(
            'audit-log/index',
            compact('logs', 'modules', 'actions', 'actors', 'filters', 'activeFilters'),
            ['datatables', 'datatables-export', 'select2'],
            ['audit-log/index-audit'],
            ['audit-log/audit-log']
        );
    }

    /**
     * Downloads the audit log as a PDF, respecting the same filters as index().
     */
    public function export(): void
    {
        $activeFilters = $this->readFilters();

        $limit      = AuditLogPdfExporter::MAX_ROWS + 1;
        $rows       = $this->logModel->getAll($activeFilters, $limit);
        $truncated  = count($rows) === $limit;

        if ($truncated) {
            $rows = array_slice($rows, 0, AuditLogPdfExporter::MAX_ROWS);
        }

        $user = Auth::user();
        $dateFrom = $activeFilters['date_from'] ?? '';
        $dateTo   = $activeFilters['date_to'] ?? '';

        $dateRange = '';
        if ($dateFrom !== '' || $dateTo !== '') {
            $dateRange = 'Period: '
                . ($dateFrom ?: 'beginning') . ' to ' . ($dateTo ?: date('Y-m-d'));
        }

        $meta = [
            'title'        => 'Audit Log Report',
            'date_range'   => $dateRange,
            'generated_at' => 'Generated: ' . date('Y-m-d H:i:s'),
            'generated_by' => 'Generated by: ' . ($user['name'] ?? 'Unknown'),
            'truncated'    => $truncated,
        ];

        AuditLogger::log(
            'audit_log',
            'export',
            'Audit log exported to PDF',
            [
                'rows'     => count($rows),
                'filters'  => $activeFilters,
                'truncated' => $truncated,
            ]
        );

        $exporter  = new AuditLogPdfExporter();
        $pdfBytes  = $exporter->render($rows, $meta);
        $filename  = 'audit-log_' . date('Y-m-d') . '.pdf';

        header('Content-Type: application/pdf');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($pdfBytes));
        echo $pdfBytes;
        exit;
    }

    /**
     * Reads and filters raw GET parameters for the audit log.
     *
     * @return array<string, string>
     */
    private function rawFilters(): array
    {
        return [
            'module'    => trim($_GET['module']    ?? ''),
            'action'    => trim($_GET['action']    ?? ''),
            'actor_id'  => trim($_GET['actor_id']  ?? ''),
            'date_from' => trim($_GET['date_from'] ?? ''),
            'date_to'   => trim($_GET['date_to']   ?? ''),
        ];
    }

    /**
     * Returns only non-empty filter values for the model.
     *
     * @return array<string, string|int>
     */
    private function readFilters(): array
    {
        return array_filter($this->rawFilters(), fn ($v) => $v !== '');
    }
}
