<?php

declare(strict_types=1);

namespace Tests\Unit\Services;

use App\Services\AuditLogPdfExporter;
use Tests\TestCase;

class AuditLogPdfExporterTest extends TestCase
{
    private AuditLogPdfExporter $exporter;

    protected function setUp(): void
    {
        parent::setUp();
        $this->exporter = new AuditLogPdfExporter();
    }

    public function test_render_returns_valid_pdf_bytes(): void
    {
        $rows = $this->fixtureRows(5);
        $meta = $this->fixtureMeta();

        $pdf = $this->exporter->render($rows, $meta);

        $this->assertStringStartsWith('%PDF-', $pdf);
        $this->assertGreaterThan(1000, strlen($pdf));
    }

    public function test_render_with_empty_rows_returns_valid_pdf(): void
    {
        $pdf = $this->exporter->render([], $this->fixtureMeta());

        $this->assertStringStartsWith('%PDF-', $pdf);
    }

    public function test_render_with_utf8_names_does_not_throw(): void
    {
        $rows = [
            [
                'created_at'   => '2026-09-09 10:30:00',
                'actor_label'  => 'José Andrés Meneces López',
                'module'       => 'users',
                'action'       => 'create',
                'description'  => 'Usuario creado: Ñuñez — "comillas"',
                'ip_address'   => '192.168.1.1',
                'actor_id'     => 1,
                'user_name'    => 'José',
                'user_first_surname' => 'Meneces',
                'user_email'   => 'jose@test.com',
            ],
        ];

        $pdf = $this->exporter->render($rows, $this->fixtureMeta());

        $this->assertStringStartsWith('%PDF-', $pdf);
    }

    public function test_render_includes_truncation_notice_when_flagged(): void
    {
        $rows = $this->fixtureRows(2);
        $meta = $this->fixtureMeta();
        $meta['truncated'] = true;

        $pdf = $this->exporter->render($rows, $meta);

        $this->assertStringStartsWith('%PDF-', $pdf);
        $this->assertGreaterThan(1000, strlen($pdf));
    }

    public function test_max_rows_constant_is_5000(): void
    {
        $this->assertSame(5000, AuditLogPdfExporter::MAX_ROWS);
    }

    /**
     * @param int $count
     * @return array
     */
    private function fixtureRows(int $count): array
    {
        $rows = [];
        for ($i = 0; $i < $count; $i++) {
            $rows[] = [
                'created_at'         => '2026-09-09 10:00:' . str_pad((string) $i, 2, '0', STR_PAD_LEFT),
                'actor_label'        => 'Test User',
                'module'             => 'users',
                'action'             => 'create',
                'description'        => 'User created: Test User',
                'ip_address'         => '127.0.0.1',
                'actor_id'           => 1,
                'user_name'          => 'Test',
                'user_first_surname' => 'User',
                'user_email'         => 'test@test.com',
            ];
        }
        return $rows;
    }

    /**
     * @return array
     */
    private function fixtureMeta(): array
    {
        return [
            'title'        => 'Audit Log Report',
            'date_range'   => '2026-01-01 to 2026-09-09',
            'generated_at' => 'Generated: 2026-09-09 12:00:00',
            'generated_by' => 'Generated by: Admin',
            'truncated'    => false,
        ];
    }
}
